[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wde_whos"
authors = [
    { name = "Elkin Giovanni Romero Bustamante", email = "gromero@aquaveo.com" },
]
dynamic = ["version", "description"]
